@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmVhNDMxZTU5MmM2ZTkzNmNhYjA0NyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNzg2MTcwNCwiZXhwIjoxNzM4MjA3MzA0fQ.6rEaIjB7XNqql8ao83OdPC8XFtqyOiXnb0Tsrw0t9Rs

### Login Admin
POST http://localhost:5003/login
Content-Type: application/json

{
  "username":  "Admin",
  "password": "Admin1234!"
}

### Menampilkan data user
GET http://localhost:5003/users
Authorization: Bearer {{token}}
Content-Type: application/json

### Menampilkan data fetch
GET http://localhost:5003/fetch
Authorization: Bearer {{token}}
Content-Type: application/json  

### Menampilkan data header
GET http://localhost:5003/header
Authorization: Bearer {{token}}
Content-Type: application/json

### Menampilkan key-code
GET http://localhost:5003/key-code
Authorization: Bearer {{token}}
Content-Type: application/json

###
### Menambah patient
POST http://localhost:5003/patient
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "fullname": "bagus", 
  "placeBirth": "banyumas", 
  "dateBirth": "1/5/2001", 
  "gender": "male", 
  "address": "Sokaraja", 
  "work": "oke", 
  "phone": "01234567898",
  "mother": "bagus",
  "citizenship": "WNI",
  "religion": "Islam",
  "maritalStatus": "belum kawin"
}

### Menampilkan data pasien
GET http://localhost:5003/patient?search=us
Authorization: Bearer {{token}}
Content-Type: application/json

### Menampilkan data pasien Encrypt
GET http://localhost:5003/encrypt/patient
Authorization: Bearer {{token}}
Content-Type: application/json

### Menampilkan detail pasien
GET http://localhost:5003/patient/6793447bd33d2ac1584f88be
Authorization: Bearer {{token}}
Content-Type: application/json

### Update patient
PUT http://localhost:5003/patient/6793447bd33d2ac1584f88be
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "fullname": "sumantry", 
  "placeBirth": "banyumas", 
  "dateBirth": "1/5/2001", 
  "gender": "male", 
  "address": "Sokaraja", 
  "work": "oke", 
  "phone": "012345678988",
  "mother": "bagus",
  "citizenship": "WNI",
  "religion": "Islam",
  "maritalStatus": "belum kawin"
}

### hapus pasien
delete http://localhost:5003/patient/67934d44061280baa2363c87
Authorization: Bearer {{token}}
Content-Type: application/json

###
### add medical record
POST http://localhost:5003/rekam-medis
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "date": "1/5/2001", 
  "diagnosis": "oke", 
  "therapy": "oke", 
  "service": "oke", 
  "description": "oke", 
  "patientId": "6793447bd33d2ac1584f88be"
}

### get medical record
get http://localhost:5003/rekam-medis
Authorization: Bearer {{token}}
Content-Type: application/json

### get medical record by patient
get http://localhost:5003/rekam-medis/patient/6793447bd33d2ac1584f88be
Authorization: Bearer {{token}}
Content-Type: application/json

### get medical record by patient Decrypt
get http://localhost:5003/decrypt/rekam-medis/patient/6793447bd33d2ac1584f88be
Authorization: Bearer {{token}}
Content-Type: application/json

### get medical detail
get http://localhost:5003/rekam-medis/6795b8c370ac834ba2c56624
Authorization: Bearer {{token}}
Content-Type: application/json

### get medical record Decrypt
get http://localhost:5003/decrypt/rekam-medis?search=sip
Authorization: Bearer {{token}}
Content-Type: application/json